// Maps the country names the Ergast/Jolpica API returns for circuit
// locations to ISO 3166-1 alpha-3 codes for react-world-flags.
// Covers current and recent F1 host countries; unknown names just render
// without a flag (the components pass fallback={null}).
export const countryToCode = {
  Australia: "AUS",
  Austria: "AUT",
  Azerbaijan: "AZE",
  Bahrain: "BHR",
  Belgium: "BEL",
  Brazil: "BRA",
  Canada: "CAN",
  China: "CHN",
  France: "FRA",
  Germany: "DEU",
  Hungary: "HUN",
  India: "IND",
  Italy: "ITA",
  Japan: "JPN",
  Korea: "KOR",
  Malaysia: "MYS",
  Mexico: "MEX",
  Monaco: "MCO",
  Morocco: "MAR",
  Netherlands: "NLD",
  Portugal: "PRT",
  Qatar: "QAT",
  Russia: "RUS",
  "Saudi Arabia": "SAU",
  Singapore: "SGP",
  "South Korea": "KOR",
  Spain: "ESP",
  Switzerland: "CHE",
  Turkey: "TUR",
  UAE: "ARE",
  UK: "GBR",
  "United Arab Emirates": "ARE",
  "United Kingdom": "GBR",
  "United States": "USA",
  USA: "USA",
  Vietnam: "VNM",
};
